apiVersion: v1
items:
- kind: "BuildConfig"
  apiVersion: "v1"
  metadata:
    name: "tasks-pipeline"
  spec:
    source:
      type: "Git"
      contextDir: "openshift-tasks/"
      git:
        uri: "https://github.com/jameshbarton/advdev_homework_template"
    strategy:
      type: "JenkinsPipeline"
      jenkinsPipelineStrategy:
        jenkinsfilePath: Jenkinsfile
        env:
        - name: GUID
          value: "b397"
        - name: REPO
          value: "https://github.com/jameshbarton/advdev_homework_template.git"
        - name: CLUSTER
          value: "https://master.na311.openshift.opentlc.com"
kind: List
metadata: []
